package com.codex.refactor.smell.detectors;

import com.codex.refactor.analysis.CommentInfo;
import com.codex.refactor.analysis.JavaMethodInfo;
import com.codex.refactor.smell.BadSmell;
import com.codex.refactor.smell.BookBadSmellDetector;
import com.codex.refactor.smell.SmellAnalysisContext;
import com.codex.refactor.smell.SmellFinding;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;

public final class CommentsBadSmellDetector extends BookBadSmellDetector {
    private static final Set<String> DEBT_MARKERS = Set.of(
            "todo", "fixme", "hack", "workaround", "temporary", "temp", "xxx"
    );
    private static final Set<String> BENIGN_CONTEXT_TERMS = Set.of(
            "license", "copyright", "generated", "autogenerated", "noinspection",
            "suppress", "rfc", "http", "https", "protocol", "spec", "standard",
            "compatibility", "backward compatible", "external", "third-party",
            "security", "constant-time", "performance", "benchmark"
    );
    private static final Set<String> STRUCTURE_COMMENT_STARTS = Set.of(
            "validate", "check", "calculate", "compute", "prepare", "build",
            "parse", "normalize", "save", "load", "fetch", "update", "render",
            "step", "phase", "section", "first", "then", "finally"
    );

    public CommentsBadSmellDetector() {
        super(BadSmell.COMMENTS);
    }

    @Override
    public boolean isImplemented() {
        return true;
    }

    @Override
    public List<SmellFinding> detect(SmellAnalysisContext context) {
        List<CommentFact> comments = context.analysis().comments().stream()
                .map(CommentFact::from)
                .toList();
        List<SmellFinding> findings = new ArrayList<>();

        comments.stream()
                .filter(CommentFact::debtMarker)
                .forEach(comment -> findings.add(commentFinding(
                        comment,
                        "debt_marker_comment",
                        "low",
                        "medium",
                        "Comment marks unfinished, temporary, or compensating design work.",
                        "Resolve the underlying design issue or track it outside the code when it is not useful to readers."
                )));

        comments.stream()
                .filter(CommentFact::commentedOutCode)
                .filter(comment -> !comment.debtMarker())
                .forEach(comment -> findings.add(commentFinding(
                        comment,
                        "commented_out_code",
                        "medium",
                        "high",
                        "Comment appears to contain disabled source code.",
                        "Remove commented-out code and rely on version control, or restore it as live code with tests."
                )));

        context.analysis().methods().stream()
                .map(method -> methodCandidate(method, comments))
                .flatMap(List::stream)
                .map(this::methodFinding)
                .forEach(findings::add);

        return DetectorSupport.fallbackIfEmpty(findings, smell(), context);
    }

    private SmellFinding commentFinding(
            CommentFact comment,
            String signal,
            String severity,
            String confidence,
            String description,
            String suggestion
    ) {
        return DetectorSupport.finding(
                smell(),
                severity,
                confidence,
                "comment",
                comment.line(),
                comment.line(),
                DetectorSupport.evidence(
                        "signal", signal,
                        "comment", comment.text(),
                        "normalized_comment", comment.content()
                ),
                description,
                suggestion
        );
    }

    private SmellFinding methodFinding(MethodCommentCandidate candidate) {
        JavaMethodInfo method = candidate.method();
        return DetectorSupport.finding(
                smell(),
                candidate.severity(),
                candidate.confidence(),
                method.name(),
                method.startLine(),
                method.endLine(),
                candidate.evidence(),
                "Method uses comments to explain hidden structure in complex or lengthy code.",
                "Extract named functions or introduce intention-revealing variables so the code carries the explanation."
        );
    }

    private static List<MethodCommentCandidate> methodCandidate(JavaMethodInfo method, List<CommentFact> comments) {
        List<CommentFact> internalComments = comments.stream()
                .filter(comment -> comment.line() >= method.startLine() && comment.line() <= method.endLine())
                .filter(comment -> !comment.debtMarker())
                .filter(comment -> !comment.commentedOutCode())
                .filter(comment -> !comment.benignContext())
                .toList();
        if (internalComments.isEmpty()) {
            return List.of();
        }

        List<CommentFact> structureComments = internalComments.stream()
                .filter(CommentFact::structureExplanation)
                .toList();
        int commentCount = internalComments.size();
        double commentDensity = (double) commentCount / Math.max(1, method.physicalLines());
        boolean complexEnough = method.physicalLines() >= 18
                || method.cyclomaticComplexity() >= 4
                || method.maxNestingDepth() >= 2;
        boolean explanatoryCluster = structureComments.size() >= 2 && complexEnough;
        boolean denseCommentary = commentCount >= 3 && commentDensity >= 0.15 && complexEnough;
        boolean longCommentedMethod = method.physicalLines() > 24 && commentCount >= 1;
        if (!explanatoryCluster && !denseCommentary && !longCommentedMethod) {
            return List.of();
        }

        String signal;
        if (explanatoryCluster) {
            signal = "structure_explaining_comments";
        } else if (denseCommentary) {
            signal = "comment_dense_complex_method";
        } else {
            signal = "long_method_with_internal_comments";
        }
        return List.of(new MethodCommentCandidate(
                method,
                signal,
                internalComments,
                structureComments,
                commentDensity
        ));
    }

    private static boolean containsAny(String value, Set<String> candidates) {
        return candidates.stream().anyMatch(value::contains);
    }

    private static boolean startsWithAnyToken(String value, Set<String> candidates) {
        String first = firstToken(value);
        return candidates.contains(first);
    }

    private static String firstToken(String value) {
        String trimmed = value.trim();
        if (trimmed.isBlank()) {
            return "";
        }
        int firstSpace = trimmed.indexOf(' ');
        String token = firstSpace >= 0 ? trimmed.substring(0, firstSpace) : trimmed;
        return token.replaceAll("[^a-z0-9_-]", "");
    }

    private static String stripCommentMarkers(String text) {
        String normalized = text == null ? "" : text.trim();
        boolean changed;
        do {
            changed = false;
            String next = normalized
                    .replaceFirst("^//+\\s*", "")
                    .replaceFirst("^#+\\s*", "")
                    .replaceFirst("^--+\\s*", "")
                    .replaceFirst("^/\\*+\\s*", "")
                    .replaceFirst("^\\*+/?\\s*", "")
                    .replaceFirst("^<!--\\s*", "")
                    .replaceFirst("\\s*-->$", "")
                    .replaceFirst("\\s*\\*/$", "")
                    .trim();
            if (!next.equals(normalized)) {
                changed = true;
                normalized = next;
            }
        } while (changed);
        return normalized;
    }

    private record CommentFact(
            int line,
            String text,
            String content,
            String lower,
            boolean debtMarker,
            boolean commentedOutCode,
            boolean benignContext,
            boolean structureExplanation
    ) {
        static CommentFact from(CommentInfo comment) {
            String content = stripCommentMarkers(comment.text());
            String lower = content.toLowerCase(Locale.ROOT);
            boolean debtMarker = containsAny(lower, DEBT_MARKERS);
            boolean commentedOutCode = looksLikeCommentedOutCode(content, lower);
            boolean benignContext = !debtMarker && containsAny(lower, BENIGN_CONTEXT_TERMS);
            boolean structureExplanation = !benignContext && looksLikeStructureExplanation(lower);
            return new CommentFact(
                    comment.line(),
                    comment.text(),
                    content,
                    lower,
                    debtMarker,
                    commentedOutCode,
                    benignContext,
                    structureExplanation
            );
        }

        private static boolean looksLikeCommentedOutCode(String content, String lower) {
            if (content.isBlank()) {
                return false;
            }
            String trimmed = content.trim();
            if (lower.matches("^\\s*(if|for|while|switch|catch|synchronized)\\s*\\(.*")) {
                return true;
            }
            if (lower.matches("^\\s*(case\\b.*:|default\\s*:).*")) {
                return true;
            }
            if (lower.matches("^\\s*(return|throw)\\b.+;\\s*$")) {
                return true;
            }
            if (lower.matches("^\\s*(class|interface|enum|function|def|fn|func)\\s+[a-z_$][\\w$]*.*")) {
                return true;
            }
            if (lower.matches("^\\s*(select\\b.+\\bfrom\\b|insert\\b.+\\binto\\b|update\\b.+\\bset\\b|delete\\b.+\\bfrom\\b).*")) {
                return true;
            }
            if (content.matches(".*[;{}].*")
                    && lower.matches(".*\\b(return|throw|new|var|let|const|int|string|boolean|public|private|void)\\b.*")) {
                return true;
            }
            if (looksLikeDeclarationOrAssignment(trimmed, lower)) {
                return true;
            }
            return looksLikeInvocation(trimmed)
                    && !lower.matches(".*\\b(see|todo|fixme|rfc|http|https)\\b.*");
        }

        private static boolean looksLikeDeclarationOrAssignment(String content, String lower) {
            if (!content.endsWith(";") && !content.contains("=")) {
                return false;
            }
            return lower.matches("^\\s*(public|private|protected|static|final|var|let|const|int|long|double|float|boolean|string|char)\\b.*")
                    || content.matches("^\\s*[A-Z][\\w$<>\\[\\], ?]*\\s+[a-zA-Z_$][\\w$]*\\s*(=|;|\\().*");
        }

        private static boolean looksLikeInvocation(String content) {
            return content.matches("^\\s*[a-zA-Z_$][\\w$]*(\\.[a-zA-Z_$][\\w$]*)+\\s*\\(.*")
                    || content.matches("^\\s*[a-zA-Z_$][\\w$]*\\s*\\([^)]*\\)\\s*;?\\s*$");
        }

        private static boolean looksLikeStructureExplanation(String lower) {
            if (lower.isBlank()) {
                return false;
            }
            if (startsWithAnyToken(lower, STRUCTURE_COMMENT_STARTS)) {
                return true;
            }
            return lower.matches(".*\\b(step|phase|section)\\s+[0-9a-z]+\\b.*")
                    || lower.matches(".*\\b(loop|branch|fallback|happy path|edge case)\\b.*");
        }
    }

    private record MethodCommentCandidate(
            JavaMethodInfo method,
            String signal,
            List<CommentFact> comments,
            List<CommentFact> structureComments,
            double commentDensity
    ) {
        String severity() {
            return structureComments.size() >= 3 || commentDensity >= 0.25 ? "medium" : "low";
        }

        String confidence() {
            return structureComments.size() >= 2 ? "medium" : "low";
        }

        Map<String, Object> evidence() {
            List<CommentFact> examples = comments.stream()
                    .sorted(Comparator.comparingInt(CommentFact::line))
                    .limit(5)
                    .toList();
            return DetectorSupport.evidence(
                    "signal", signal,
                    "physical_lines", method.physicalLines(),
                    "cyclomatic_complexity", method.cyclomaticComplexity(),
                    "max_nesting_depth", method.maxNestingDepth(),
                    "comment_count", comments.size(),
                    "structure_comment_count", structureComments.size(),
                    "comment_density", commentDensity,
                    "comment_lines", comments.stream().map(CommentFact::line).toList(),
                    "comment_examples", examples.stream().map(CommentFact::content).distinct().toList()
            );
        }
    }
}
